# Generated by Django 6.1.1 on 2026-09-06 21:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("language_practice", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Curso",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("titulo", models.CharField(max_length=200)),
                ("slug", models.SlugField(blank=True, max_length=200, unique=True)),
                ("descripcion", models.TextField()),
                ("categoria", models.CharField(db_index=True, max_length=100)),
                (
                    "nivel",
                    models.CharField(
                        choices=[
                            ("PRIMARIA", "Primaria"),
                            ("SECUNDARIA", "Secundaria"),
                            ("BACHILLERATO", "Bachillerato"),
                            ("UNIVERSITARIO", "Universitario"),
                            ("POSGRADO", "Posgrado"),
                            ("LIBRE", "Libre"),
                        ],
                        default="LIBRE",
                        max_length=20,
                    ),
                ),
                (
                    "estado",
                    models.CharField(
                        choices=[
                            ("BORRADOR", "Borrador"),
                            ("PUBLICADO", "Publicado"),
                            ("ARCHIVADO", "Archivado"),
                        ],
                        default="BORRADOR",
                        max_length=20,
                    ),
                ),
                ("duracion_horas", models.IntegerField(default=10)),
                ("fecha_creacion", models.DateTimeField(auto_now_add=True)),
                ("fecha_actualizacion", models.DateTimeField(auto_now=True)),
                ("imagen_url", models.URLField(blank=True, null=True)),
                ("palabras_clave", models.CharField(blank=True, max_length=500)),
                (
                    "precio",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
                ),
            ],
            options={
                "ordering": ["-fecha_creacion"],
            },
        ),
        migrations.CreateModel(
            name="Insignia",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=100)),
                ("descripcion", models.TextField()),
                (
                    "tipo",
                    models.CharField(
                        choices=[
                            ("CURSO", "Curso"),
                            ("PRACTICA", "Práctica"),
                            ("EVALUACION", "Evaluación"),
                            ("RACHA", "Racha"),
                            ("ESPECIAL", "Especial"),
                            ("CERTIFICACION", "Certificación"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "nivel",
                    models.CharField(
                        choices=[
                            ("BRONCE", "Bronce"),
                            ("PLATA", "Plata"),
                            ("ORO", "Oro"),
                            ("DIAMANTE", "Diamante"),
                            ("EXPERTO", "Experto"),
                        ],
                        default="BRONCE",
                        max_length=20,
                    ),
                ),
                ("icono", models.CharField(default="fa-star", max_length=50)),
                ("color", models.CharField(default="#FFD700", max_length=20)),
                ("puntos_requeridos", models.IntegerField(default=0)),
                ("requisitos", models.JSONField(blank=True, default=dict)),
                ("is_active", models.BooleanField(default=True)),
                ("fecha_creacion", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "Insignia",
                "verbose_name_plural": "Insignias",
                "ordering": ["nivel", "tipo"],
            },
        ),
        migrations.CreateModel(
            name="EntregaArchivo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("titulo", models.CharField(max_length=200)),
                ("descripcion", models.TextField(blank=True, null=True)),
                (
                    "tipo_archivo",
                    models.CharField(
                        choices=[
                            ("AUDIO", "Audio"),
                            ("IMAGEN", "Imagen"),
                            ("PDF", "PDF"),
                            ("DOCUMENTO", "Documento"),
                            ("VIDEO", "Video"),
                            ("OTRO", "Otro"),
                        ],
                        default="DOCUMENTO",
                        max_length=20,
                    ),
                ),
                (
                    "archivo",
                    models.FileField(max_length=500, upload_to="entregas/%Y/%m/%d/"),
                ),
                ("nombre_original", models.CharField(max_length=255)),
                ("tamanio_bytes", models.BigIntegerField(default=0)),
                ("extension", models.CharField(blank=True, max_length=10)),
                (
                    "estado",
                    models.CharField(
                        choices=[
                            ("PENDIENTE", "Pendiente de revisión"),
                            ("APROBADO", "Aprobado"),
                            ("RECHAZADO", "Rechazado"),
                            ("REVISION", "En revisión"),
                        ],
                        default="PENDIENTE",
                        max_length=20,
                    ),
                ),
                ("comentario_profesor", models.TextField(blank=True, null=True)),
                ("calificacion", models.FloatField(blank=True, null=True)),
                ("fecha_entrega", models.DateTimeField(auto_now_add=True)),
                ("fecha_revision", models.DateTimeField(blank=True, null=True)),
                ("ip_origen", models.GenericIPAddressField(blank=True, null=True)),
                ("user_agent", models.TextField(blank=True, null=True)),
                (
                    "usuario",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="entregas",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-fecha_entrega"],
            },
        ),
        migrations.CreateModel(
            name="ComentarioEntrega",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("comentario", models.TextField()),
                ("fecha", models.DateTimeField(auto_now_add=True)),
                (
                    "usuario",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "entrega",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="comentarios",
                        to="core.entregaarchivo",
                    ),
                ),
            ],
            options={
                "ordering": ["fecha"],
            },
        ),
        migrations.CreateModel(
            name="Evaluacion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("titulo", models.CharField(max_length=200)),
                ("descripcion", models.TextField(blank=True, null=True)),
                (
                    "tipo",
                    models.CharField(
                        choices=[
                            ("EXAMEN", "Examen"),
                            ("PRACTICA", "Práctica"),
                            ("PROYECTO", "Proyecto"),
                            ("FINAL", "Final"),
                        ],
                        default="EXAMEN",
                        max_length=20,
                    ),
                ),
                ("preguntas", models.JSONField(blank=True, default=list)),
                ("puntaje_maximo", models.IntegerField(default=100)),
                ("duracion_minutos", models.IntegerField(default=30)),
                ("nota_minima", models.IntegerField(default=60)),
                ("fecha_publicacion", models.DateTimeField(auto_now_add=True)),
                ("fecha_limite", models.DateTimeField(blank=True, null=True)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "curso",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="evaluaciones",
                        to="core.curso",
                    ),
                ),
                (
                    "leccion",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="evaluaciones",
                        to="language_practice.lesson",
                    ),
                ),
            ],
            options={
                "ordering": ["-fecha_publicacion"],
            },
        ),
        migrations.AddField(
            model_name="entregaarchivo",
            name="evaluacion",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="entregas",
                to="core.evaluacion",
            ),
        ),
        migrations.CreateModel(
            name="Practica",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("titulo", models.CharField(max_length=200)),
                ("descripcion", models.TextField(blank=True, null=True)),
                (
                    "tipo",
                    models.CharField(
                        choices=[
                            ("EJERCICIO", "Ejercicio"),
                            ("QUIZ", "Quiz"),
                            ("DIAGNOSTICO", "Diagnóstico"),
                            ("REPASO", "Repaso"),
                        ],
                        default="EJERCICIO",
                        max_length=20,
                    ),
                ),
                ("preguntas", models.JSONField(blank=True, default=list)),
                ("puntaje_maximo", models.IntegerField(default=100)),
                ("duracion_minutos", models.IntegerField(default=15)),
                ("orden", models.IntegerField(default=0)),
                ("is_active", models.BooleanField(default=True)),
                ("fecha_creacion", models.DateTimeField(auto_now_add=True)),
                (
                    "curso",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="practicas",
                        to="core.curso",
                    ),
                ),
                (
                    "leccion",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="practicas",
                        to="language_practice.lesson",
                    ),
                ),
            ],
            options={
                "ordering": ["orden", "fecha_creacion"],
            },
        ),
        migrations.AddField(
            model_name="entregaarchivo",
            name="practica",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="entregas",
                to="core.practica",
            ),
        ),
        migrations.CreateModel(
            name="EjercicioInteractivo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "tipo",
                    models.CharField(
                        choices=[
                            ("OPCION_MULTIPLE", "Opción Múltiple"),
                            ("VERDADERO_FALSO", "Verdadero/Falso"),
                            ("COMPLETAR", "Completar"),
                            ("ORDENAR", "Ordenar"),
                            ("RELACIONAR", "Relacionar"),
                            ("TEXTO", "Texto Libre"),
                        ],
                        default="OPCION_MULTIPLE",
                        max_length=20,
                    ),
                ),
                ("pregunta", models.TextField()),
                ("opciones", models.JSONField(blank=True, default=list)),
                ("respuesta_correcta", models.TextField()),
                ("explicacion", models.TextField(blank=True, null=True)),
                ("puntaje", models.IntegerField(default=5)),
                ("orden", models.IntegerField(default=0)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "evaluacion",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ejercicios",
                        to="core.evaluacion",
                    ),
                ),
                (
                    "practica",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ejercicios",
                        to="core.practica",
                    ),
                ),
            ],
            options={
                "ordering": ["orden"],
            },
        ),
        migrations.CreateModel(
            name="Certificacion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("puntaje_obtenido", models.FloatField(default=0.0)),
                ("porcentaje", models.FloatField(default=0.0)),
                (
                    "estado",
                    models.CharField(
                        choices=[
                            ("PENDIENTE", "Pendiente"),
                            ("COMPLETADO", "Completado"),
                            ("REVOCADO", "Revocado"),
                        ],
                        default="PENDIENTE",
                        max_length=20,
                    ),
                ),
                ("fecha_inicio", models.DateTimeField(auto_now_add=True)),
                ("fecha_completado", models.DateTimeField(blank=True, null=True)),
                ("fecha_vencimiento", models.DateTimeField(blank=True, null=True)),
                (
                    "codigo_verificacion",
                    models.CharField(blank=True, max_length=100, unique=True),
                ),
                ("observaciones", models.TextField(blank=True, null=True)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "usuario",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="certificaciones",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "curso",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="certificaciones",
                        to="core.curso",
                    ),
                ),
                (
                    "evaluacion",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="certificaciones",
                        to="core.evaluacion",
                    ),
                ),
                (
                    "practica",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="certificaciones",
                        to="core.practica",
                    ),
                ),
            ],
            options={
                "verbose_name": "Certificación",
                "verbose_name_plural": "Certificaciones",
                "ordering": ["-fecha_completado"],
            },
        ),
        migrations.CreateModel(
            name="ProgresoCurso",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("practicas_completadas", models.IntegerField(default=0)),
                ("evaluaciones_completadas", models.IntegerField(default=0)),
                ("puntaje_total", models.FloatField(default=0.0)),
                ("lecciones_vistas", models.IntegerField(default=0)),
                ("ultimo_acceso", models.DateTimeField(auto_now=True)),
                ("completado", models.BooleanField(default=False)),
                (
                    "curso",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="progresos",
                        to="core.curso",
                    ),
                ),
                (
                    "usuario",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="progresos",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-ultimo_acceso"],
            },
        ),
        migrations.CreateModel(
            name="PuntajeUsuario",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("puntos_totales", models.IntegerField(default=0)),
                ("puntos_curso", models.JSONField(blank=True, default=dict)),
                ("ejercicios_resueltos", models.IntegerField(default=0)),
                ("ejercicios_correctos", models.IntegerField(default=0)),
                ("racha_actual", models.IntegerField(default=0)),
                ("racha_maxima", models.IntegerField(default=0)),
                ("ultimo_ejercicio", models.DateTimeField(blank=True, null=True)),
                (
                    "nivel_general",
                    models.CharField(
                        choices=[
                            ("BRONCE", "Bronce"),
                            ("PLATA", "Plata"),
                            ("ORO", "Oro"),
                            ("DIAMANTE", "Diamante"),
                            ("EXPERTO", "Experto"),
                        ],
                        default="BRONCE",
                        max_length=20,
                    ),
                ),
                ("fecha_actualizacion", models.DateTimeField(auto_now=True)),
                (
                    "usuario",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="puntaje",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-puntos_totales"],
            },
        ),
        migrations.CreateModel(
            name="RecursoEducativo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre_archivo", models.CharField(max_length=500)),
                ("ruta_completa", models.CharField(max_length=1000, unique=True)),
                ("extension", models.CharField(blank=True, max_length=20, null=True)),
                ("categoria", models.CharField(db_index=True, max_length=100)),
                (
                    "tipo_contenido",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                ("tamanio_bytes", models.IntegerField()),
                ("fecha_creacion", models.DateTimeField()),
                ("fecha_modificacion", models.DateTimeField()),
                ("descripcion", models.TextField(blank=True, null=True)),
                ("etiquetas", models.TextField(blank=True, null=True)),
                ("importado_el", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["categoria", "nombre_archivo"],
                "indexes": [
                    models.Index(
                        fields=["categoria"], name="core_recurs_categor_c1ff19_idx"
                    ),
                    models.Index(
                        fields=["nombre_archivo"], name="core_recurs_nombre__231adb_idx"
                    ),
                ],
            },
        ),
        migrations.AddField(
            model_name="curso",
            name="recursos",
            field=models.ManyToManyField(
                blank=True, related_name="cursos", to="core.recursoeducativo"
            ),
        ),
        migrations.CreateModel(
            name="InsigniaUsuario",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("fecha_obtenida", models.DateTimeField(auto_now_add=True)),
                ("visible", models.BooleanField(default=True)),
                ("progreso", models.FloatField(default=0.0)),
                (
                    "insignia",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="usuarios",
                        to="core.insignia",
                    ),
                ),
                (
                    "usuario",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="insignias",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-fecha_obtenida"],
                "unique_together": {("usuario", "insignia")},
            },
        ),
        migrations.AddIndex(
            model_name="entregaarchivo",
            index=models.Index(
                fields=["usuario"], name="core_entreg_usuario_9144ea_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="entregaarchivo",
            index=models.Index(
                fields=["practica"], name="core_entreg_practic_2195a4_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="entregaarchivo",
            index=models.Index(
                fields=["evaluacion"], name="core_entreg_evaluac_98dade_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="entregaarchivo",
            index=models.Index(fields=["estado"], name="core_entreg_estado_f2a269_idx"),
        ),
        migrations.AlterUniqueTogether(
            name="certificacion",
            unique_together={("usuario", "curso")},
        ),
        migrations.AlterUniqueTogether(
            name="progresocurso",
            unique_together={("usuario", "curso")},
        ),
        migrations.AddIndex(
            model_name="curso",
            index=models.Index(
                fields=["categoria"], name="core_curso_categor_baa930_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="curso",
            index=models.Index(fields=["nivel"], name="core_curso_nivel_799b03_idx"),
        ),
        migrations.AddIndex(
            model_name="curso",
            index=models.Index(fields=["estado"], name="core_curso_estado_3887ff_idx"),
        ),
    ]
