# Generated by Django 6.1.1 on 2026-09-06 22:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="PerfilUsuario",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "rol",
                    models.CharField(
                        choices=[
                            ("SUPERUSUARIO", "Superusuario"),
                            ("PROFESOR", "Profesor"),
                            ("ESTUDIANTE", "Estudiante"),
                            ("ADMIN", "Administrador"),
                        ],
                        default="ESTUDIANTE",
                        max_length=20,
                    ),
                ),
                (
                    "identificacion",
                    models.CharField(blank=True, max_length=20, null=True),
                ),
                ("telefono", models.CharField(blank=True, max_length=20, null=True)),
                ("direccion", models.TextField(blank=True, null=True)),
                ("fecha_nacimiento", models.DateField(blank=True, null=True)),
                (
                    "foto",
                    models.ImageField(blank=True, null=True, upload_to="perfiles/"),
                ),
                ("biografia", models.TextField(blank=True, null=True)),
                ("redes_sociales", models.JSONField(blank=True, default=dict)),
                ("fecha_registro", models.DateTimeField(auto_now_add=True)),
                ("ultimo_acceso", models.DateTimeField(blank=True, null=True)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "cursos_impartidos",
                    models.ManyToManyField(
                        blank=True, related_name="profesores", to="core.curso"
                    ),
                ),
                (
                    "cursos_inscritos",
                    models.ManyToManyField(
                        blank=True,
                        related_name="estudiantes_inscritos",
                        to="core.curso",
                    ),
                ),
                (
                    "usuario",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="perfil",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Perfil de Usuario",
                "verbose_name_plural": "Perfiles de Usuarios",
                "ordering": ["-fecha_registro"],
            },
        ),
    ]
