# Generated by Django 6.1.1 on 2026-09-06 22:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_perfilusuario"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Notificacion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "tipo",
                    models.CharField(
                        choices=[
                            ("MENSAJE", "Nuevo mensaje"),
                            ("CURSO", "Curso asignado"),
                            ("EVALUACION", "Evaluación disponible"),
                            ("CERTIFICADO", "Certificado obtenido"),
                            ("SISTEMA", "Notificación del sistema"),
                        ],
                        default="SISTEMA",
                        max_length=20,
                    ),
                ),
                ("titulo", models.CharField(max_length=200)),
                ("contenido", models.TextField()),
                ("url", models.CharField(blank=True, max_length=500, null=True)),
                ("leido", models.BooleanField(default=False)),
                ("fecha_creacion", models.DateTimeField(auto_now_add=True)),
                (
                    "usuario",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notificaciones",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-fecha_creacion"],
            },
        ),
        migrations.CreateModel(
            name="Mensaje",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("asunto", models.CharField(max_length=200)),
                ("contenido", models.TextField()),
                (
                    "tipo",
                    models.CharField(
                        choices=[
                            ("PRIVADO", "Privado"),
                            ("GRUPO", "Grupo"),
                            ("SISTEMA", "Sistema"),
                        ],
                        default="PRIVADO",
                        max_length=20,
                    ),
                ),
                (
                    "estado",
                    models.CharField(
                        choices=[
                            ("ENVIADO", "Enviado"),
                            ("LEIDO", "Leído"),
                            ("RESPONDIDO", "Respondido"),
                            ("ARCHIVADO", "Archivado"),
                        ],
                        default="ENVIADO",
                        max_length=20,
                    ),
                ),
                ("fecha_envio", models.DateTimeField(auto_now_add=True)),
                ("fecha_leido", models.DateTimeField(blank=True, null=True)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "adjuntos",
                    models.ManyToManyField(blank=True, to="core.entregaarchivo"),
                ),
                (
                    "curso",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="mensajes",
                        to="core.curso",
                    ),
                ),
                (
                    "destinatario",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="mensajes_recibidos",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "remitente",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="mensajes_enviados",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-fecha_envio"],
                "indexes": [
                    models.Index(
                        fields=["remitente"], name="core_mensaj_remiten_386328_idx"
                    ),
                    models.Index(
                        fields=["destinatario"], name="core_mensaj_destina_48e77b_idx"
                    ),
                    models.Index(
                        fields=["curso"], name="core_mensaj_curso_i_df0123_idx"
                    ),
                    models.Index(
                        fields=["estado"], name="core_mensaj_estado_5e18d3_idx"
                    ),
                ],
            },
        ),
    ]
